// <auto-generated />
using System;
using InventoryService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace RepositoryService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250126211653_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RepositoryService.Domain.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientFullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClientPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StoreUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalItems")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("af4ed62e-f786-487e-9149-73810453a833"),
                            ClientFullName = "Иванов Иван Иванович",
                            ClientPhone = "+7900-000-00-00",
                            CreationDate = new DateTime(2025, 1, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            StoreUntil = new DateTime(2025, 2, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            TotalItems = 2,
                            TotalPrice = 22040m
                        },
                        new
                        {
                            Id = new Guid("ee2ca227-74c9-4131-acc0-c25171562598"),
                            ClientFullName = "Петров Пётр Петрович",
                            ClientPhone = "+7911-111-11-11",
                            CreationDate = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            StoreUntil = new DateTime(2025, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            TotalItems = 1,
                            TotalPrice = 7970m
                        });
                });

            modelBuilder.Entity("RepositoryService.Domain.Models.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8a9215b6-705c-451f-a2c4-bdd643d74a7a"),
                            OrderId = new Guid("af4ed62e-f786-487e-9149-73810453a833"),
                            ProductId = new Guid("4cc140dc-410b-4a1f-8e57-8c11c8debe8d"),
                            Quantity = 2,
                            UnitPrice = 11020m
                        },
                        new
                        {
                            Id = new Guid("d6dac720-bd3b-460c-8757-2cd9398882ed"),
                            OrderId = new Guid("ee2ca227-74c9-4131-acc0-c25171562598"),
                            ProductId = new Guid("11ea3f23-f3d7-4834-ab3d-247f41517da2"),
                            Quantity = 1,
                            UnitPrice = 7970m
                        });
                });

            modelBuilder.Entity("RepositoryService.Domain.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Article")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11ea3f23-f3d7-4834-ab3d-247f41517da2"),
                            Article = "SLEG-900-1TCS",
                            Description = "Накопитель SSD 1Tb ADATA Legend 900 (SLEG-900-1TCS) - это высококачественное хранилище данных для вашего компьютера",
                            Name = "SSD 1Tb ADATA Legend 900 (SLEG-900-1TCS)",
                            Price = 7970m,
                            QuantityInStock = 20
                        },
                        new
                        {
                            Id = new Guid("4cc140dc-410b-4a1f-8e57-8c11c8debe8d"),
                            Article = "WD43PURZ",
                            Name = "4Tb SATA-III WD Purple (WD43PURZ)",
                            Price = 11020m,
                            QuantityInStock = 2
                        });
                });

            modelBuilder.Entity("RepositoryService.Domain.Models.OrderItem", b =>
                {
                    b.HasOne("RepositoryService.Domain.Models.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RepositoryService.Domain.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("RepositoryService.Domain.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
